(write-line "Hello World")
(write '(+(* 2 2)(* 4 4)))
(defvar x 10)
(defvar y 34.567)
(defvar ch nil)
(defvar n 123.78)
(defvar bg 11.0e+4)
(defvar r 124/2)
(print (type-of x))
(print (type-of y))
(print (type-of n))
(print (type-of ch))
(print (type-of bg))
(print (type-of r))

(defmacro yumi-macro (num)
  (setq num 10)
  (print num))

(setq x 25)
(print x)
(yumi-macro x)
